language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t 129037/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true 129037/docker-react npm run test